vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    candidate_cv:
      uri_prefix: /images/candidats
      upload_destination: "%kernel.project_dir%/public/images/candidats"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
